apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ez99szqze-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ez99szqze-nodejs 
  name: ez99szqze-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ez99szqze-nodejs 
